### ISSUE TITLE
Google Drive links are not publicly accessible

### ISSUE THREAD

**Issue by helgster77** [BlackKakapo/Icelandic-Word-Embedding#3]
Sorry to raise another issue, but the updated links are not publicly available, I get a Google Drive page where I can "Request Access". Any way this can be fixed? Thanks!

**Comment by BlackKakapo** [comment]
Hello
Now everyone with links has access to the models

Respectfully

**Comment by helgster77** [comment]
Thank you, I tried this in my RAG application and it seems to work well!
